version: '3.1'
volumes: 
  dados:
services: 
    db: 
      image: postgres:9.6
      volumes: 
        - dados:/var/lib/postgresql/data
        - ./scripts:/scripts
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      container_name: "postgres"
      environment:
        POSTGRES_PASSWORD: admin@123
      ports: 
        - 5432:5432

    minio: 
      image: minio/minio:RELEASE.2021-08-25T00-41-18Z
      command: server --console-address ":9001" /data
      expose:
        - "9000"
        - "9001"
      container_name: "minio"
      environment:
        - "MINIO_ROOT_USER=minio"
        - "MINIO_ROOT_PASSWORD=minio123"
      volumes: 
        - ../storage/minio:/data
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3        
      ports: 
        - 9000:9000
        - 9001:9001

    api:
      image: jeumichelin/api-registro-candidatura
      container_name: "api"
      ports: 
        - 5100:80
      depends_on: 
        - db