// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegistroCandidatura.Infra.Data.Context;

namespace RegistroCandidatura.Infra.Data.Migrations
{
    [DbContext(typeof(RegistroCandidaturaContext))]
    partial class RegistroCandidaturaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("RegistroCandidatura.Domain.Entities.RegistroCandidatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("NOME");

                    b.Property<decimal>("PretensaoSalarial")
                        .HasColumnType("numeric")
                        .HasColumnName("PRETENSAO_SALARIAL");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text")
                        .HasColumnName("SOBRENOME");

                    b.Property<string>("Vaga")
                        .HasColumnType("text")
                        .HasColumnName("VAGA");

                    b.HasKey("Id");

                    b.ToTable("RegistroCandidatura");
                });
#pragma warning restore 612, 618
        }
    }
}
